---

name: "Charts Release"
description: "Update helm charts versions in values.yaml file and create a release draft"

inputs:
  release:
    description: "Release version"
    required: true
    type: string
  config-file:
    description: "Path to the configuration file for updating versions in values.yaml"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Update chart version"
      id: update-chart-version
      run: |
        import os
        import yaml

        with open('${{ inputs.config-file }}', 'r') as f:
          data = yaml.safe_load(f)
        for chart in data['charts']:
          chart_file = chart['chart_file']
          values_file = chart['values_file']
          # Update chart version in Chart.yaml
          release = "${{ inputs.release }}"
          print(f"{chart['name']} Version: ${{ inputs.release }}")
          os.system(f"sed -i 's|^version:.*|{ver_str}|' {chart_file}")
          # Update image version in values.yaml
          image_ver = chart['version'].replace('${release}', '${{ inputs.release }}')
          for image in chart['image']:
            print(f"Updating image version: {image} to {image_ver}")
            search_str = image.replace('${version}', '')
            os.system(f"sed -i 's|{search_str}.*|{search_str}{image_ver}|' {values_file}")
      shell: python
    - name: "Commit changed files"
      run: |
        git config --global user.name "qubership-actions[bot]"
        git config --global user.email "qubership-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Set chart and images versions to release [skip ci]"
        git push
